# 04 NumPy Exercises by Jose Portila

Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks, and then you'll be asked some more complicated questions.

#### 1. Import NumPy as np

since numpy is not installed in my console I need to run `pip install numpy` before I import the library

In [3]:
#pip install numpy

In [4]:
import numpy as np

#### 2. Create an array of 10 zeros 

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 3. Create an array of 10 ones

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

#### 4. Create an array of 10 fives

In [10]:
np.ones(10) * 5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

#### 5. Create an array of the integers from 10 to 50

In [13]:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

#### 6. Create an array of all the even integers from 10 to 50

In [14]:
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

#### 7. Create a 3x3 matrix with values ranging from 0 to 8

In [19]:
np.random.randint(9, 
                  size=(3,3))

array([[8, 2, 3],
       [5, 4, 0],
       [8, 0, 0]], dtype=int32)

#### 8. Create a 3x3 identity matrix

In [21]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 9. Use NumPy to generate a random number between 0 and 1

In [24]:
np.random.rand(1)

array([0.22461101])

#### 10. Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [28]:
np.random.normal(0, 1, 25)

array([ 0.40628152,  1.42160193, -0.58253699,  0.56472587, -1.87090233,
       -1.27129356, -0.75798895,  0.92246176,  0.04286007,  1.29234785,
       -1.7810017 ,  1.65022354,  0.53168931, -1.72958678, -0.62158636,
       -0.70904255,  0.63969814, -0.40583426, -1.09162961, -0.32256902,
       -1.83863331, -0.84484207,  0.05325984,  0.28158056,  0.31650978])

#### 11. Create the following matrix:

In [33]:
np.round(np.random.rand(10,10),2)

array([[0.2 , 0.69, 0.12, 0.28, 0.43, 0.17, 0.32, 0.21, 0.02, 0.15],
       [0.44, 0.85, 0.5 , 0.78, 0.53, 0.93, 0.09, 0.67, 0.11, 0.36],
       [0.71, 0.77, 0.05, 0.15, 0.13, 0.79, 0.51, 0.99, 0.72, 0.05],
       [0.98, 0.36, 0.6 , 0.63, 1.  , 0.49, 0.68, 0.01, 0.09, 0.92],
       [0.46, 0.56, 0.65, 0.82, 0.98, 0.16, 0.13, 0.  , 0.39, 0.16],
       [0.31, 0.17, 0.57, 0.1 , 0.02, 0.48, 0.98, 0.56, 0.98, 0.21],
       [0.3 , 0.35, 0.5 , 0.4 , 0.31, 0.61, 0.2 , 0.35, 0.63, 0.99],
       [0.98, 0.  , 0.85, 0.13, 0.92, 0.02, 0.45, 0.65, 0.65, 0.79],
       [0.64, 0.77, 0.77, 0.39, 0.51, 0.3 , 0.06, 0.63, 0.  , 0.74],
       [0.15, 0.87, 0.14, 0.63, 0.69, 0.43, 0.42, 0.13, 0.23, 0.72]])

#### 12. Create an array of 20 linearly spaced points between 0 and 1:

In [34]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

## Numpy Indexing and Selection

Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [35]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

#### 13. Write code to produce the following output (from referrring to mat): 

``` 
array([[12, 13, 14, 15],  
       [17, 18, 19, 20],  
       [22, 23, 24, 25]])
```

In [43]:
mat[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

#### 14. Write code below to produce the following output (from referring to mat): 
``` 20 ```

In [49]:
print(mat[3,4])

20


#### 15. Write code below to produce the following output (from referring to mat):
  
```
array([[ 2],
       [ 7],
       [12]])
```

In [53]:
mat[0:3,1:2] #row, column

array([[ 2],
       [ 7],
       [12]])

#### 16. Write code that produces the following output (from referring to mat)

``` array([21, 22, 23, 24, 25])```

In [54]:
mat[4:5,]

array([[21, 22, 23, 24, 25]])

#### 17. Write code that produces the following output (from referring to mat)

```
array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```

In [55]:
mat[3:5,]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Now do the following

#### 18. Get the sum of all the values in mat

In [57]:
print(np.sum(mat))

325


#### 19. Get the standard deviation of the values in mat

In [59]:
print(np.std(mat))

7.211102550927978


#### 20. Get the sum of all the columns in mat

In [61]:
np.sum(mat, axis=0)

array([55, 60, 65, 70, 75])