# Assignment 1

**Deadline.** The submission date for your cohort will be published on Canvas.

**The Assignment Task.** There are 6 exercises in this first assignment. Each completed exercise is awarded 5 points for a total of 30 points. The second assignment will be worth the remaining 70 points. In order to pass this Part 1 course, you will need to achieve at least 40 points out of 100.

**Submission.** Please email your solutions and your completed Declaration of Authorship (DoA) form to weeklyclasses@conted.ox.ac.uk 

In [64]:
## Let's import the libraries we are going to use later on
import numpy as np
import pandas as pd

# Let's set the precision for NumPy and Pandas
np.set_printoptions(precision=3)
pd.options.display.float_format = '{:,.2f}'.format

## Exercises on Data Structures

### 1. Compute statistics on a Python list [5 points]
Given the following list
```
l = [12, 45, 12, 999, 10, 8, 76, 20, 10, 10, 7, 70, 17]
```
Compute the mean, the median and the standard deviation of the values in the list, using only built-in functionalities of python (no imported libraries, no NumPy or Pandas)

In [20]:
# I am importing the statisitcs library to double-check my answers
import statistics

l = [12, 45, 12, 999, 10, 8, 76, 20, 10, 10, 7, 70, 17]

# Write your solution here

print('\033[1m Mean \033[0m')
print('-----------------------------------------------------------------------')
#dividing the sum of the list over its lenth to get the mean/average
l_mean = sum(l)/len(l)

print('The mean of list l is:', '\033[1m' , l_mean , '\033[0m')
print('Checking with the *mean()* function:', '\033[1m' , statistics.mean(l) , '\033[0m')
print()


print('\033[1m Median \033[0m')
print('-----------------------------------------------------------------------')
#updating list l by sorting all the values from least to greatest. This is needed to find the middle value
l = sorted(l)
#creating a variable for the length of list l which is 13
l_len = len(l)

#dividing the list length by 2 using integer divission since I want a whole number.
#the middle value is at position 7 in the list (in terms of length), 
#but since indexing starts at 0 I can keep this value and will obtain the middle value
l_median_index = l_len//2

#now I am printing the number that I obtained of the index
print('The median of list l is:', '\033[1m' ,l[l_median_index] , '\033[0m')
print('Checking with the *median()* function:', '\033[1m' , statistics.median(l) , '\033[0m')
print()

print('\033[1m Standard Deviation \033[0m')
print('-----------------------------------------------------------------------')

##the first step to find the standard deviation is to calculate the mean, which I have already done
#print(l_mean)

##the second step is to subtract each list value from the mean and to square that result
##I am creating a new list to store these values since I might need to original list in the future
w = []
i = 0
while i < l_len:
  w.append( (l[i] - l_mean)**2 )
  i = i + 1

##the third step is to then get the sum of the new values and divide it by the number in the list (the length)
##note: I am calculating the standard deviation of a sample so I am going to subtract the list length by 1 (which is 12)
##      if I was calculating the standard deviation of the population then I would divide by the full list length (which is 13)

sd_third_step = sum(w)/(l_len-1)

##the fourth step is to square the previous result
l_sample_sd = sd_third_step**0.5

print('The standard deviation of the sample of list l is:', '\033[1m' , l_sample_sd , '\033[0m')
print('Checking with the *stdev()* function:', '\033[1m' , statistics.stdev(l) , '\033[0m')


 Mean 
-----------------------------------------------------------------------
The mean of list l is:  99.6923076923077 
Checking with the *mean()* function:  99.6923076923077 

 Median 
-----------------------------------------------------------------------
The median of list l is:  12 
Checking with the *median()* function:  12 

 Standard Deviation 
-----------------------------------------------------------------------
The standard deviation of the sample of list l is:  271.2457018447127 
Checking with the *stdev()* function:  271.2457018447127 


### 2. Create a dictionary from a list of tuples (records) [5 points]

Given the following list of tuples, each one holding a record
```
records = [
    ('author', 'title', 'publication_year', 'page_count'), 
    ('J. R. R. Tolkien', 'The Fellowship of the Ring', 1954, 398),
    ('J. K. Rowling', 'Harry Potter and the Philosopher\'s stone', 1996, 223),
    ('Evelyn Waugh', 'Brideshead Revisited', 1945, 402),
    ('Philip K. Dick', 'Ubik', 1969, 202),
    ('Thomas Pynchon', "Gravity's Rainbow", 1973, 760),
    ('Stephen King', 'The Stand', 1978, 829)
]
```
Convert them into a list of dictionaries, using the first tuple as keys for all the dictionaries and all the other tuples as values, one per dictionary. 
Expected result:

```
books = [{'author': 'J. R. R. Tolkien',
  'title': 'The Fellowship of the Ring',
  'publication_year': 1954,
  'page_count': 398},
 {'author': 'J. K. Rowling',
  'title': "Harry Potter and the Philosopher's stone",
  'publication_year': 1996,
  'page_count': 223},
 {'author': 'Evelyn Waugh',
  'title': 'Brideshead Revisited',
  'publication_year': 1945,
  'page_count': 402},
 {'author': 'Philip K. Dick',
  'title': 'Ubik',
  'publication_year': 1969,
  'page_count': 202},
 {'author': 'Thomas Pynchon',
  'title': "Gravity's Rainbow",
  'publication_year': 1973,
  'page_count': 760},
 {'author': 'Stephen King',
  'title': 'The Stand',
  'publication_year': 1978,
  'page_count': 829}]
```

In [63]:
records = [
    ('author', 'title', 'publication_year', 'page_count'), 
    ('J. R. R. Tolkien', 'The Fellowship of the Ring', 1954, 398),
    ('J. K. Rowling', 'Harry Potter and the Philosopher\'s stone', 1996, 223),
    ('Evelyn Waugh', 'Brideshead Revisited', 1945, 402),
    ('Philip K. Dick', 'Ubik', 1969, 202),
    ('Thomas Pynchon', "Gravity's Rainbow", 1973, 760),
    ('Stephen King', 'The Stand', 1978, 829)
]

## Write your solution here
books = []
new_dictionary = {}

#I am obtaining the length of the records list so I can iterate over each item (the tuples)
records_length_7 = len(records) #length is 7

#I am also obtaining the length of each tuple so I can iterate over each item in the tuple
#note: I check that all tuple lenghts are equal in the while loop 
tuple_length_4 = len(records[0]) #length is 4

index = 0
while index < records_length_7:
    #the print statment below checks if all tuples have the same length and shows the index
    #print('\033[1m index: \033[0m', index, ' | ' ,'\033[1m tuple length: \033[0m',len(records[index]),' | ',records[index]) #I am printing each item and the index to understand the code better
    
    #now I index over each item in the tuple. this is where I bring the tuple_length_4 variable
    tuple_index = 0
    while tuple_index < tuple_length_4:
        #the print statment below prints the tuple index and each item in the tuple
        #print('\033[1m  > tuple index: \033[0m', tuple_index, ' | ' ,records[index][tuple_index]) #I am printing each item and the index to understand the code better
        
        #all the values that are beyond the fist tuple in the original list are the actual values that need to be inputted in the dictionary keys.
        #because of this I all going to use the tuple that is **ahead** of the first tuple (which is the tuple which includes all the keys)
        #because of this I need to make use of 6 rounds of iterations (instead of 7) which is why I make a if statement that does not take into account the 6th iteration
        if index <= 5:
            #now I create a dictionary keys from the first tuple. the tuple_index variable ensures that all the keys (ex.'author', 'title', 'publication_year', 'page_count') are added as the for loop iterates each time
            #I then assign the key value by obtaining each item of all the tuples that are below the first tuple (or the tuple that has a zero iteration)
            new_dictionary[records[0][tuple_index]] = records[index+1][tuple_index]
            
            #the print statement below prints the dictionary and can be used to check whether the correct values are assigned
            #print(new_dictionary)
        
        tuple_index = tuple_index + 1
        
    # again, same reasoning as before. since there are 6 tuples that are below the 1st one I only need 5 iterations (in other words, 6 rounds since iterations include 0)
    if index <= 5:
        books.append(new_dictionary.copy()) #I am adding the dictionaries to the list 'books'
        #print(new_dictionary)
    
    index = index + 1 #adding one make sures that I iterate over each list item
   
print('books = ',books)
print()
print('-----------------','\033[1m','Printing the dictionaries by each line','\033[0m','---------------------')
for x in range(len(books)):
    print('\033[1m index: \033[0m', x, ' | ' ,'\033[1m Dictionary: \033[0m', books[x])

print()
print('-----------------','\033[1m','Printing the dictionaries as a dataframe','\033[0m','---------------------')
print(pd.DataFrame(books))

#note: I used the code below to see how the original list (results) would look like as a dataframe. 
#      I wanted to highlight the difference between having a list of dictionaries and a list of tuples

#print()
#print('-----------------','\033[1m','Printing the original list as a dataframe','\033[0m','---------------------')
#print(pd.DataFrame(records))
    

books =  [{'author': 'J. R. R. Tolkien', 'title': 'The Fellowship of the Ring', 'publication_year': 1954, 'page_count': 398}, {'author': 'J. K. Rowling', 'title': "Harry Potter and the Philosopher's stone", 'publication_year': 1996, 'page_count': 223}, {'author': 'Evelyn Waugh', 'title': 'Brideshead Revisited', 'publication_year': 1945, 'page_count': 402}, {'author': 'Philip K. Dick', 'title': 'Ubik', 'publication_year': 1969, 'page_count': 202}, {'author': 'Thomas Pynchon', 'title': "Gravity's Rainbow", 'publication_year': 1973, 'page_count': 760}, {'author': 'Stephen King', 'title': 'The Stand', 'publication_year': 1978, 'page_count': 829}]

-----------------  Printing the dictionaries by each line  ---------------------
 index:  0  |   Dictionary:  {'author': 'J. R. R. Tolkien', 'title': 'The Fellowship of the Ring', 'publication_year': 1954, 'page_count': 398}
 index:  1  |   Dictionary:  {'author': 'J. K. Rowling', 'title': "Harry Potter and the Philosopher's stone", 'publication_

## Exercises on Numpy

For these exercises we will work on the IRIS dataset, a very popular multivariate dataset for data anaylisis, first introduced by Ronald Fisher in 1936.

See more about the IRIS dataset heare: https://archive.ics.uci.edu/ml/datasets/Iris

The data source is the file `iris.data` retrieved from the Web. It contains the data for this example in comma separated values (CSV) format. The number of columns is 5 and the number of rows is 150. The data set is composed of 50 samples from each of three species of Iris Flower: Iris Setosa, Iris Virginica and Iris Versicolor. Four features were measured from each sample: the length and the width of the sepals and petals, in centimetres. Based on the combination of these four features, Fisher developed a linear discriminant model to distinguish the species one from each other.

The variables are:

    sepal_length: Sepal length, in centimeters.
    sepal_width: Sepal width, in centimeters.
    petal_length: Petal length, in centimeters.
    petal_width: Petal width, in centimeters.

The three categories of Irises are: 'Iris Setosa', 'Iris Versicolor', and 'Iris Virginica'. 

Let's first import the `iris` dataset as a 1-dimensional array of tuples.

In [65]:
# Input:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', 
                     names=['sepal length', 'sepal width', 'petal length', 'petal width', 'species'],
                     dtype=[np.float32, np.float32, np.float32, np.float32, '|S15']
)

In [66]:
iris

array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, b'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, b'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, b'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, b'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, b'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, b'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, b'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, b'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, b'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, b'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, b'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, b'Iris-setosa'),
       (4.

### 3A. How to convert a 1d array of tuples to a 2d numpy array [2 points]

Exercise: convert the `iris` 1D array to a numeric-only 2D array `iris_data` by omitting the species text field. Create a `iris_label` 1D array containing only the species text field. Keep the same indexing/order as in the original array.

In [70]:
## Write your solution here

#creating the 2D `iris_data` array
iris_data = np.array([list(row)[0:4] for row in iris]) #going through each row in the iris dataset and am gathering the first 4 data points and am putting it into a list to make a 2D array
#print(iris_data.ndim) #output: 2 - this is the dimension of the dataset

print('\033[1m','-->iris_data','\033[0m')
print(iris_data[:5])
print()

#creating 1D `iris_data` array
iris_label = np.array([list(row)[4] for row in iris])
#print(iris_label.ndim) #output: 1 - this is the dimension of the dataset

print('\033[1m','-->iris_label','\033[0m')
print(iris_label[:5])

 -->iris_data 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]

 -->iris_label 
[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


### 3B. Split the IRIS dataset by Label [3 points]


Split the dataset in `iris_data` according to the labels `iris_labels`. 

In [82]:
# Write your solution here

iris_dict_by_labels = {} #creating the dictionary that groups the `iris_data` values by the flower species

###printing the unique values in the `iris_label` dataset
#print(np.unique(iris_label)) #output: [b'Iris-setosa' b'Iris-versicolor' b'Iris-virginica']

###the for loop will assign the appropriate data values to the flower species key in the dictionary
for key in np.unique(iris_label):   
    iris_dict_by_labels[key] = iris_data[iris_label == key]
    
#print(iris_dict_by_labels) #printing the whole dictionary

#I am using this for loop to print out the first 5 rows of each key
for key in iris_dict_by_labels:
    print('--->',key)
    print(iris_dict_by_labels[key][:5])

---> b'Iris-setosa'
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
---> b'Iris-versicolor'
[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]
---> b'Iris-virginica'
[[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]


### 4. Compute statistics with Numpy [5 points]

1) For each flower species compute the key statistics for `sepal width`:
- mean
- median
- standard deviation

Answer the following questions:

a) Which is the flower type with the largest mean value for `sepal_width`?
> **Answer**: Iris-setosa since it has a **3.418 cm.** `sepal_width` mean 

b) Which is the flower type with the smallest median value for `sepal_width`?
> **Answer**: Iris-versicolor since it has a **2.8 cm.** `sepal_width` median
    
    
2 ) Compute the correlation matrix between `sepal_width` and `petal_length` for the three scpecies. Which is the species that shows the highest correlation among the two parameters?
> **Answer**:The species `Iris-versicolor` has a correlation coeficcient of **0.561** between the `sepal_width` and `petal_length` variables. This is the highest correlation coeficcient when compared with the other species

### Tables

> Table of `sepal_width` variable key statistics

|                             |   Iris-setosa  |  Iris-versicolor  | Iris-virginica  |
|-----------------------------|----------------|-------------------|-----------------|
|Mean                         |3.418 cm.       | 2.77 cm.          | 2.974 cm.       |
|Median                       |3.4 cm.         | 2.8 cm.           | 3 cm.           |
|Population Standard Deviation|0.377 cm.       | 0.311 cm.         | 0.319 cm.       |
|Sample Standard Deviation    |0.381 cm.       | 0.314 cm.         | 0.322 cm.       |

> Table of correlation coefficients between `sepal_width` and `petal_length` for the three scpecies

|                                                            |   Iris-setosa  |  Iris-versicolor  | Iris-virginica  |
|------------------------------------------------------------|----------------|-------------------|-----------------|
|Correlation Coefficient of `sepal_width` and `petal_length` |0.177           |0.561              |0.401            |

### Calculating the Key Statistics and finding the largest mean and smallest medain value of `sepal_width`

In [105]:
### Compute mean, median, and standard deviation for `sepal width` here:

column_stats = {} #I am creating a dictionary for the key statisitics of `sepal_width`

for key in iris_dict_by_labels:
    column_stats[key] = {
        'mean' : np.mean(iris_dict_by_labels[key], axis=0),
        'median' :  np.median(iris_dict_by_labels[key], axis=0),
        'standard deviation (population)': np.std(iris_dict_by_labels[key], axis=0),
        'standard deviation (sample)' : np.std(iris_dict_by_labels[key], axis = 0, ddof=1)        
    }
    

#I am creating these 2 dictionaries to store the mean and median values for `sepal_width` only. I will then use these values to compute the largest mean and smallest median
sepal_width_means = {}
sepal_width_medians = {}

#print(column_stats) #this prints the `sepal_width` statistics dictionary
#I am using the for loop below to print the `sepal_width` statistics contents in a nicer format
for key in column_stats:
    print('##########',key,'##########')
    
    for sub_key in column_stats[key]:
        print('\033[1m',sub_key,'\033[0m')
        print(column_stats[key][sub_key])
        
        #this if-else statment gathers the mean and median values of `sepal_width` and assigns it to the species dictionary key that it belongs to 
        if sub_key == 'mean':
            sepal_width_means[key] = column_stats[key][sub_key][1]
        elif sub_key == 'median':
            sepal_width_medians[key] = column_stats[key][sub_key][1]

    print()

###these print statments just check and see if I made the two dictionaries `sepal_width_means` and `sepal_width_medians` correctly
#print(sepal_width_means) #output: {b'Iris-setosa': 3.4180002, b'Iris-versicolor': 2.77, b'Iris-virginica': 2.9740002}
#print(sepal_width_medians) #output: {b'Iris-setosa': 3.4, b'Iris-versicolor': 2.8, b'Iris-virginica': 3.0}

### checking the larget mean and smallest median values of `sepal_width`
print()
print('---------------Checking the highest mean value and lowest median value of `sepal_width`-------------------')
print()
max_mean_species = max(sepal_width_means, key=sepal_width_means.get) #this variable gives of the dictionary key that has the highest mean value
print('The species that has the \033[1mhighest\033[0m mean value is:',
      '\033[1m',max_mean_species,'\033[0m',
      'and the value of the mean is',
      '\033[1m',sepal_width_means[max_mean_species],'\033[0m')

min_median_species = min(sepal_width_medians, key=sepal_width_medians.get) #this variable gives of the dictionary key that has the lowest median
print('The species that has the \033[1mlowest\033[0m median value is:',
      '\033[1m',min_median_species,'\033[0m',
      'and the value of the median is',
      '\033[1m',sepal_width_medians[min_median_species],'\033[0m')

########## b'Iris-setosa' ##########
 mean 
[5.006 3.418 1.464 0.244]
 median 
[5.  3.4 1.5 0.2]
 standard deviation (population) 
[0.349 0.377 0.172 0.106]
 standard deviation (sample) 
[0.352 0.381 0.174 0.107]

########## b'Iris-versicolor' ##########
 mean 
[5.936 2.77  4.26  1.326]
 median 
[5.9  2.8  4.35 1.3 ]
 standard deviation (population) 
[0.511 0.311 0.465 0.196]
 standard deviation (sample) 
[0.516 0.314 0.47  0.198]

########## b'Iris-virginica' ##########
 mean 
[6.588 2.974 5.552 2.026]
 median 
[6.5  3.   5.55 2.  ]
 standard deviation (population) 
[0.629 0.319 0.546 0.272]
 standard deviation (sample) 
[0.636 0.322 0.552 0.275]


---------------Checking the highest mean value and lowest median value of `sepal_width`-------------------

The species that has the highest mean value is:  b'Iris-setosa'  and the value of the mean is  3.4180002 
The species that has the lowest median value is:  b'Iris-versicolor'  and the value of the median is  2.8 


### Computing the correlation matrix/coefficient of `sepal_width` and `petal_length`

In [144]:
### Compute the correlation coefficients here
y = 0 #this is dummy count variable that I used to ensure that I was printing the correct number of rows
s_p_width_length = {} #creating a dictionary that only contains the `sepal_width` and `petal_length` values 

for key in iris_dict_by_labels:
    sample_list = [] #this is a temporary list that will store all the data values of `sepal_width` and `petal_length`
    i = 0
    #print(dataset[1:3])
    #print(key)
    while i < 50: #this while loop makes sure to go through each dataset 50 times since each species has 50 rows of data
        sample_list = np.append(sample_list, iris_dict_by_labels[key][i][1:3])
        y = y+1
        i = i +1
    
    sample_list = sample_list.reshape(50, 2) #changing the list to match the proper array structure in the original dataset
    s_p_width_length[key] = sample_list #the i variable makes sure to iterate every row in the `iris_dict_by_labels` dictionary
        
    #print(y) #this ensures that the number of rows in each key is correct
    
### I am printing the dictionary that only contains the `sepal_width` and `petal_length` column values
#print(s_p_width_length) 

### solving for the covariance martrix
cov_mat = {
    key: dict(cov=np.cov(dataset.T, ddof=0)) for key, dataset in s_p_width_length.items()
}

#print(cov_mat)
#print('-------------------------------------')

### Compute the correlation matrix here
cor_mat = {
    key: dict(correlation_matrix=np.corrcoef(dataset.T)) for key, dataset in s_p_width_length.items()
}
#print(cor_mat)

#printing the correlation matrix in a easier to read format
for key in cor_mat:
    print('--------------------------------')
    print('#######',key,'#######')
    print('--------------------------------')
    for data in cor_mat[key]:
        print('###','\033[1m',data,'\033[0m','###')
        print(cor_mat[key][data])
    


--------------------------------
####### b'Iris-setosa' #######
--------------------------------
###  correlation_matrix  ###
[[1.    0.177]
 [0.177 1.   ]]
--------------------------------
####### b'Iris-versicolor' #######
--------------------------------
###  correlation_matrix  ###
[[1.    0.561]
 [0.561 1.   ]]
--------------------------------
####### b'Iris-virginica' #######
--------------------------------
###  correlation_matrix  ###
[[1.    0.401]
 [0.401 1.   ]]


### 5. Create a new column from existing columns of a numpy array [5 points]

Create a new column for the flower volume V in `iris`, where volume is computing according to this formula (the assumption here is that the shape of the iris flower is approximately conical):

$$ Volume = \frac{\pi \times Sepal Length^2 \times Petal Length}{3}$$

In [190]:
import math
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')

iris_2d_multidim_list = [] #I am creating this multidimensional list so I can create the dataframe in question 6

# Write your solution here
for row in iris_2d: #accessing each row in the `iris_2d` dataset
    row[0:4] = row[0:4].astype(str).astype(float) #converting all four length and width columns to a float type 
    row[4] = str(row[4], 'UTF-8') #converting the species column into a string type
    
    row = np.append(row, (math.pi* row[0]**2 * row[2])/3) #creating the volume column
    iris_2d_multidim_list.append(row) #the multidimensional list is created here and this will append the new rows
    #print((math.pi* row[0]**2 * row[2])/3 )

    #row = row.append((math.pi* row[0]**2 * row[2])/3) #I am creating the `volume` column and use the append function to add the
    #print(row)

#printing the first 5 rows of the `iris_2d_multidim_list` array
#print(iris_2d_multidim_list[:5])

#printing the values in a easy to read format
test = 0
while test < 5:
    print(iris_2d_multidim_list[test])
    test = test + 1




[5.1 3.5 1.4 0.2 'Iris-setosa' 38.13265162927291]
[4.9 3.0 1.4 0.2 'Iris-setosa' 35.200498485922445]
[4.7 3.2 1.3 0.2 'Iris-setosa' 30.0723720777127]
[4.6 3.1 1.5 0.2 'Iris-setosa' 33.238050274980004]
[5.0 3.6 1.4 0.2 'Iris-setosa' 36.65191429188092]


### 6A. Convert the numpy array into a pandas DataFrame [2 points]

Convert the all the columns of the numpy array into a Pandas DataFrame. Test this has worked successfully by printing a random sample of ten rows (records) from the new DataFrame. 

In [191]:
# Write your solution here


flower_volume_dataframe = pd.DataFrame(iris_2d_multidim_list) #converting the array `iris_2d_multidim_list` into a dataframe
flower_volume_dataframe = flower_volume_dataframe.rename(columns ={0:'sepal_length',1:'sepal_width',2:'petal_length',3:'petal_width',4:'species',5 : 'volume'} ) #defining the column names

#print(flower_volume_dataframe[:10]) #printing 10 rows of the the dataframe
print()
print('----------------Random Sample of 10 Rows---------------------')
print(flower_volume_dataframe.sample(n = 10, replace = False)) #printing a random sample of 10 rows from the dataframe


   sepal_length  sepal_width  petal_length  petal_width      species  volume
0          5.10         3.50          1.40         0.20  Iris-setosa   38.13
1          4.90         3.00          1.40         0.20  Iris-setosa   35.20
2          4.70         3.20          1.30         0.20  Iris-setosa   30.07
3          4.60         3.10          1.50         0.20  Iris-setosa   33.24
4          5.00         3.60          1.40         0.20  Iris-setosa   36.65
5          5.40         3.90          1.70         0.40  Iris-setosa   51.91
6          4.60         3.40          1.40         0.30  Iris-setosa   31.02
7          5.00         3.40          1.50         0.20  Iris-setosa   39.27
8          4.40         2.90          1.40         0.20  Iris-setosa   28.38
9          4.90         3.10          1.50         0.10  Iris-setosa   37.71

----------------Random Sample of 10 Rows---------------------
     sepal_length  sepal_width  petal_length  petal_width          species  \
38          

### 6B. Display the mean flower volume for each of the flower types [3 points]
Providing that you've calculated the flower volume for each row in Q5, now calculate and display the mean volumes for each of the three flower types.

In [194]:
#Write your solution here

#print(flower_volume_dataframe['species'].unique()) # output: ['Iris-setosa' 'Iris-versicolor' 'Iris-virginica']
# the `species_name` variable containes all of the unique flower species names in the species column
species_name_list = flower_volume_dataframe['species'].unique()

for species_name in species_name_list: #`df['species'].unique()` prints the unique values in the `species` column which are the 3 flower species
    check = flower_volume_dataframe["species"]==species_name #the `check` variable prints all the volume values for each species
    #print('-----------')
    print('The mean volume of', species_name, 'is:', flower_volume_dataframe[check]["volume"].mean())
    print('-----------')

The mean volume of Iris-setosa is: 38.76237340470947
-----------
The mean volume of Iris-versicolor is: 160.5600356287936
-----------
The mean volume of Iris-virginica is: 258.80760722723386
-----------
