# Assignment 1

**Deadline.** The submission date for your cohort will be published on Canvas.

**The Assignment Task.** There are 6 exercises in this first assignment. Each completed exercise is awarded 5 points for a total of 30 points. The second assignment will be worth the remaining 70 points. In order to pass this Part 1 course, you will need to achieve at least 40 points out of 100.

**Submission.** Please email your solutions and your completed Declaration of Authorship (DoA) form to weeklyclasses@conted.ox.ac.uk 

In [2]:
## Let's import the libraries we are going to use later on
import numpy as np
import pandas as pd

# Let's set the precision for NumPy and Pandas
np.set_printoptions(precision=3)
pd.options.display.float_format = '{:,.2f}'.format

## Exercises on Data Structures

### 1. Compute statistics on a Python list [5 points]
Given the following list
```
l = [12, 45, 12, 999, 10, 8, 76, 20, 10, 10, 7, 70, 17]
```
Compute the mean, the median and the standard deviation of the values in the list, using only built-in functionalities of python (no imported libraries, no NumPy or Pandas)

In [2]:
# Note: I am importing these modules just to check my answers
from statistics import mean 
from statistics import median
from statistics import stdev
#import statistics

l = [12, 45, 12, 999, 10, 8, 76, 20, 10, 10, 7, 70, 17]

# Write your solution here
print('\033[1m This is the Mean: \033[0m')
print('-----------------------------------------------------------------------')
print('The mean of the list is:', sum(l)/len(l))
print('When I used the *mean()* function to check my answer I get', mean(l))
print()

print('\033[1m This is the Median: \033[0m')
print('-----------------------------------------------------------------------')
## I first had to sort the list from smallest to largest to get the middle value
l = sorted(l)

## I then had to get the list length which was 13 
#print(len(l))

## To get the middle value I have to divide the length by 2 and round the value
## note: when I do rounded division python goes to lowest number so 6.5 becomes 6, not 7. Because of the low rounding
##       I need to add 1 to properly round my result 'upward'. Now I did think about the possibility that dividing the 
##       result might give a value that might be 6.2 or 7.1 which would not need the upward rounding. However, list 
##       lengths come in whole numbers that can be odd or even and odd whole numbers always need to have upward rounding
##       when divided by 2 since the division result is always has a 0.5 in it (ex. 3/2 = 1.5,  15/2 = 7.5)
      
#The middle value of this list is 7. I now have to find the number on the 6th position/index of the list
#(I am saying 6 because indexing of lists start at 0)

#print( (len(l)//2) +1 )
print('The median of the list is:', l[len(l)//2])
print('When I used the *median()* function to check my answer I get',median(l))
print()

print('\033[1m This is the Standard Deviation: \033[0m')
print('-----------------------------------------------------------------------')
## The first step in finding the standard deviation is finding the mean which was previously calculated
## The mean is: 99.6923076923077
mean_l = sum(l)/len(l)

## The second step is to subtract each data point in the list by the mean and then to square the result
## I am creating a new list to store these new values
m = []
for x in range( len(l) ):
    m.append((l[x]-(mean_l))**2 )
    
## The third step is to find the sum of the values that were calculated in step 2. 
## The sum is 882890.7692307689
#print(sum(m))

## The 3rd step is to divide the sum with the number of data points in the list
## note: the number of data points here will be subtracted by one since I am calculating the standard deviation of the sample
## Since the list is small I assumed that I am dealing with a sample which is why I calculated the standard deviation of a sample
## The result that I got is 73574.23076923074
step_three_sd = sum(m)/(len(l)-1)

## The 4th and final step is to square root your previous result
print('The standard deviation (of the sample) of the list is: ', step_three_sd**0.5 )
print('When I used the *stdev()* function to check my answer I get:', stdev(l))

 This is the Mean: 
-----------------------------------------------------------------------
The mean of the list is: 99.6923076923077
When I used the *mean()* function to check my answer I get 99.6923076923077

 This is the Median: 
-----------------------------------------------------------------------
The median of the list is: 12
When I used the *median()* function to check my answer I get 12

 This is the Standard Deviation: 
-----------------------------------------------------------------------
The standard deviation (of the sample) of the list is:  271.2457018447127
When I used the *stdev()* function to check my answer I get: 271.2457018447127


### 2. Create a dictionary from a list of tuples (records) [5 points]

Given the following list of tuples, each one holding a record
```
records = [
    ('author', 'title', 'publication_year', 'page_count'), 
    ('J. R. R. Tolkien', 'The Fellowship of the Ring', 1954, 398),
    ('J. K. Rowling', 'Harry Potter and the Philosopher\'s stone', 1996, 223),
    ('Evelyn Waugh', 'Brideshead Revisited', 1945, 402),
    ('Philip K. Dick', 'Ubik', 1969, 202),
    ('Thomas Pynchon', "Gravity's Rainbow", 1973, 760),
    ('Stephen King', 'The Stand', 1978, 829)
]
```
Convert them into a list of dictionaries, using the first tuple as keys for all the dictionaries and all the other tuples as values, one per dictionary. 
Expected result:

```
books = [{'author': 'J. R. R. Tolkien',
  'title': 'The Fellowship of the Ring',
  'publication_year': 1954,
  'page_count': 398},
 {'author': 'J. K. Rowling',
  'title': "Harry Potter and the Philosopher's stone",
  'publication_year': 1996,
  'page_count': 223},
 {'author': 'Evelyn Waugh',
  'title': 'Brideshead Revisited',
  'publication_year': 1945,
  'page_count': 402},
 {'author': 'Philip K. Dick',
  'title': 'Ubik',
  'publication_year': 1969,
  'page_count': 202},
 {'author': 'Thomas Pynchon',
  'title': "Gravity's Rainbow",
  'publication_year': 1973,
  'page_count': 760},
 {'author': 'Stephen King',
  'title': 'The Stand',
  'publication_year': 1978,
  'page_count': 829}]
```

In [40]:
import time
records = [
    ('author', 'title', 'publication_year', 'page_count'), 
    ('J. R. R. Tolkien', 'The Fellowship of the Ring', 1954, 398),
    ('J. K. Rowling', 'Harry Potter and the Philosopher\'s stone', 1996, 223),
    ('Evelyn Waugh', 'Brideshead Revisited', 1945, 402),
    ('Philip K. Dick', 'Ubik', 1969, 202),
    ('Thomas Pynchon', "Gravity's Rainbow", 1973, 760),
    ('Stephen King', 'The Stand', 1978, 829)
]

## Write your solution here

## to start off I first get the length of the records list which is 7
## This is important since I need to iterate in each item in the list
#print('The length of the list \033[1m records \033[0m is: ',len(records))

## I now want to check the length of each tuple to see if they are all the same (all tuple lengths = 4)
## knowing this will help me determine if I can succesfully convert the list to a dictionary
#for test in range(len(records)):
#    print(len(records[test]))

## I am creating a blank list and dictionary. This is so I can create the new list of dictionaries 
books = []
d = {}

## I am creating a for loop to iterate each list item. the y will represent each tuple that is iterated
for y in range(len(records)):

    # now that y represents each tuple I iterate over each item in the tuple
    # all tuple lengths are the same so I am not worried that the index will go 'out of range' when indexing each item
    # NOTE: this for loop creates the individual dictionaries. That is why I am interating all the items in each tuple
    for x in range(len(records[y])):
        
        # now in our original list the first tuple containes all the titles that are used in the dictionary (ex. 'author', 'title', 'publication_year', 'page_count')
        # because of this I will use set the dictionary to set the first items in the first tuple to be keys (this is done through d[records[0][x]] )
        # each dictionary key will then be assigned the contents in the other tuple lists that are below the first tuple
        # this is where 'y+1' comes from. It makes sure that I obtain the information from all tuples that are after the first tuple
        # but I have to add a if statement to prevent the indexing from going 'out of range' since at iteration 6 there is no tuple that will have a iteration of 7 when you do (6+1)
        if y+1 < len(records):
            d[records[0][x]] = records[y+1][x]
            #print(d)
            #time.sleep(5) #this is just to see how the code works
            
    # the same logic applies here. I know that when iteration 6 is reached there will be no tuple beyond that iteration which is why I make a if statement to avoid going 'out of bounds' in the list indexing
    # now that I have my dictionary 'd' I need to append it to the list 'books' which I created earlier
    if y+1 < len(records):
        books.append(d.copy())
        #print(y) #I am just printing the iteration of the original list of tuples to understand how the code works

## output
print('books = ', books)
print()
print('----------------- \033[1m Displaying the dictionaries in a easy to read format \033[0m ------------------------')
for index in range(len(books)):
    print(books[index])

books =  [{'author': 'J. R. R. Tolkien', 'title': 'The Fellowship of the Ring', 'publication_year': 1954, 'page_count': 398}, {'author': 'J. K. Rowling', 'title': "Harry Potter and the Philosopher's stone", 'publication_year': 1996, 'page_count': 223}, {'author': 'Evelyn Waugh', 'title': 'Brideshead Revisited', 'publication_year': 1945, 'page_count': 402}, {'author': 'Philip K. Dick', 'title': 'Ubik', 'publication_year': 1969, 'page_count': 202}, {'author': 'Thomas Pynchon', 'title': "Gravity's Rainbow", 'publication_year': 1973, 'page_count': 760}, {'author': 'Stephen King', 'title': 'The Stand', 'publication_year': 1978, 'page_count': 829}]

-----------------  Displaying the dictionaries in a easy to read format  ------------------------
{'author': 'J. R. R. Tolkien', 'title': 'The Fellowship of the Ring', 'publication_year': 1954, 'page_count': 398}
{'author': 'J. K. Rowling', 'title': "Harry Potter and the Philosopher's stone", 'publication_year': 1996, 'page_count': 223}
{'author'

In [43]:
books

[{'author': 'J. R. R. Tolkien',
  'title': 'The Fellowship of the Ring',
  'publication_year': 1954,
  'page_count': 398},
 {'author': 'J. K. Rowling',
  'title': "Harry Potter and the Philosopher's stone",
  'publication_year': 1996,
  'page_count': 223},
 {'author': 'Evelyn Waugh',
  'title': 'Brideshead Revisited',
  'publication_year': 1945,
  'page_count': 402},
 {'author': 'Philip K. Dick',
  'title': 'Ubik',
  'publication_year': 1969,
  'page_count': 202},
 {'author': 'Thomas Pynchon',
  'title': "Gravity's Rainbow",
  'publication_year': 1973,
  'page_count': 760},
 {'author': 'Stephen King',
  'title': 'The Stand',
  'publication_year': 1978,
  'page_count': 829}]

## Exercises on Numpy

For these exercises we will work on the IRIS dataset, a very popular multivariate dataset for data anaylisis, first introduced by Ronald Fisher in 1936.

See more about the IRIS dataset heare: https://archive.ics.uci.edu/ml/datasets/Iris

The data source is the file `iris.data` retrieved from the Web. It contains the data for this example in comma separated values (CSV) format. The number of columns is 5 and the number of rows is 150. The data set is composed of 50 samples from each of three species of Iris Flower: Iris Setosa, Iris Virginica and Iris Versicolor. Four features were measured from each sample: the length and the width of the sepals and petals, in centimetres. Based on the combination of these four features, Fisher developed a linear discriminant model to distinguish the species one from each other.

The variables are:

    sepal_length: Sepal length, in centimeters.
    sepal_width: Sepal width, in centimeters.
    petal_length: Petal length, in centimeters.
    petal_width: Petal width, in centimeters.

The three categories of Irises are: 'Iris Setosa', 'Iris Versicolor', and 'Iris Virginica'. 

Let's first import the `iris` dataset as a 1-dimensional array of tuples.

In [4]:
# Input:
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', 
                     names=['sepal length', 'sepal width', 'petal length', 'petal width', 'species'],
                     dtype=[np.float32, np.float32, np.float32, np.float32, '|S15']
)

In [5]:
iris

array([(5.1, 3.5, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3. , 1.4, 0.2, b'Iris-setosa'),
       (4.7, 3.2, 1.3, 0.2, b'Iris-setosa'),
       (4.6, 3.1, 1.5, 0.2, b'Iris-setosa'),
       (5. , 3.6, 1.4, 0.2, b'Iris-setosa'),
       (5.4, 3.9, 1.7, 0.4, b'Iris-setosa'),
       (4.6, 3.4, 1.4, 0.3, b'Iris-setosa'),
       (5. , 3.4, 1.5, 0.2, b'Iris-setosa'),
       (4.4, 2.9, 1.4, 0.2, b'Iris-setosa'),
       (4.9, 3.1, 1.5, 0.1, b'Iris-setosa'),
       (5.4, 3.7, 1.5, 0.2, b'Iris-setosa'),
       (4.8, 3.4, 1.6, 0.2, b'Iris-setosa'),
       (4.8, 3. , 1.4, 0.1, b'Iris-setosa'),
       (4.3, 3. , 1.1, 0.1, b'Iris-setosa'),
       (5.8, 4. , 1.2, 0.2, b'Iris-setosa'),
       (5.7, 4.4, 1.5, 0.4, b'Iris-setosa'),
       (5.4, 3.9, 1.3, 0.4, b'Iris-setosa'),
       (5.1, 3.5, 1.4, 0.3, b'Iris-setosa'),
       (5.7, 3.8, 1.7, 0.3, b'Iris-setosa'),
       (5.1, 3.8, 1.5, 0.3, b'Iris-setosa'),
       (5.4, 3.4, 1.7, 0.2, b'Iris-setosa'),
       (5.1, 3.7, 1.5, 0.4, b'Iris-setosa'),
       (4.

### 3A. How to convert a 1d array of tuples to a 2d numpy array [2 points]

Exercise: convert the `iris` 1D array to a numeric-only 2D array `iris_data` by omitting the species text field. Create a `iris_label` 1D array containing only the species text field. Keep the same indexing/order as in the original array.

#### Method Number 1

I used two methods to convert the `iris` 1D array to the `iris_data` 2D array and `iris_label` 1D array. I have shown my first method below.

In [495]:
## Write your solution here

#For my solution I decided to use a different approach to make the array (using for loops) which I have shown below
#I explored this alternative route just so I can increase my understanding of arrays and decided to show the work that I did when engaing in this process

#creating the iris_data array
#I am creating the array by going through each row in the iris dataset. I then pick the first four items in each row and create a new list which stack up on each other, creating the array
iris_data_check = np.array([list(row)[0:4] for row in iris])

#printing the output
print(f'\033[1miris_data {iris_data_check.ndim}-D array\033[0m', '|  \033[1mNote\033[0m: I have checked the array dimensions in the print statement')
print('-------------------------------------------------------------------------------------------')
print(iris_data_check[:5])
print()
print()
#creating the iris_label array
iris_label_check = np.array([list(row)[4] for row in iris])

#printing the output
print(f'\033[1miris_data {iris_label_check.ndim}-D array\033[0m', '|  \033[1mNote\033[0m: I have checked the array dimensions in the print statement')
print('-------------------------------------------------------------------------------------------')
print(iris_label_check[:5])

iris_data 2-D array |  Note: I have checked the array dimensions in the print statement
-------------------------------------------------------------------------------------------
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


iris_data 1-D array |  Note: I have checked the array dimensions in the print statement
-------------------------------------------------------------------------------------------
[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


#### Method Number 2

This is the second method that I have used to create the `iris_data` 2D array and `iris_label` 1D array. I was curious to explore and see if there is a second way to create arrays which is why I decided to include a second method on how to create arrays

- **Step 1:** In this method I will be getting all the values in a list. I would then need to convert the list into a matrix which is why my first step (this is commented) is to obtain the number of rows and columns I need for my matrix

In [ ]:
####### Alternative method of making the 'iris_data' 2D array and 'iris_label' 1D array#######

## checking the number of columns that I need in the matrix/array 
#tuple_one = list(iris)[0] #output: (5.1, 3.5, 1.4, 0.2, b'Iris-setosa') #creating a single tuple to iterate over the columns and count the number of rows that I need
#print(np.array( list(list(tuple_one)[0:4] ))) #output: [5.1 3.5 1.4 0.2]
#print(len(np.array( list(list(tuple_one)[0:4] )))) #length:4 -matrix columns

#alternative column check: I could also check the length using a for loop and calculating the length (of numbers) in each row. although this does generate a lot of 4 outputs
#for x in iris:
#    print(len(np.array( list(x)[0:4] )))

## checking the number of rows that I need in the matrix/array 
#print(len(iris)) #length is 150 - matrix rows

- **Step 2:** The code below starts making the 1D and 2D arrays. I first create the `iris_label` and `iris_data` lists and then use the `reshape()` function to convert the lists to a matrix (note: I do not use the `reshape()` function for `iris_label` since it is a 1D array and only has one column

In [506]:
my_list = [] #I am making a new list to store the array of all the numbers. I will convert this into a matrix later on
iris_label = []
iris_data = []

for y in iris: #the for loop will go through the 'iris' array and each row/tuple
    my_list = np.append(my_list, np.array( list(y)[0:4] )) #I am creating the array of all the numbers. however, this array will only inlcude the numbers separatly (it will be 1 dimensional) . I need to convert it into a matrix to make it 2-dimensional 
    iris_label = np.append(iris_label, np.array( list(y)[4] )) #I am creating a 1 dimensional array of all the flower species
    
print('The Current Dimension of the array \033[1m`my_list`\033[0m is:', my_list.ndim,'-Dimensional') #I used this print statment to see that the 'my_list' array is 1 dimensional and need to be converted to a 2D array
print('--------------------')

##I am now converting the my_list 1D array to a 2D array by converting it to a matrix 
iris_data = np.array(my_list).reshape(150,4)
##I am converting the matrix to an array since a matrix can only be 2-dimensional while an array can be n-dimensions
iris_data = np.asarray(iris_data)

#I am checking the dimensions of both arrays 
print('The Dimension of the array \033[1m`iris_data`\033[0m is now:',iris_data.ndim,'-Dimensional')
print('The Dimension of the array \033[1m`iris_label`\033[0m is:',iris_label.ndim,'-Dimensional')
print()
print()

print('----------------- \033[1m Printing the Arrays \033[0m ------------------------')

print(iris_data[:5])
print(iris_label[:5])


The Current Dimension of the array `my_list` is: 1 -Dimensional
--------------------
The Dimension of the array `iris_data` is now: 2 -Dimensional
The Dimension of the array `iris_label` is: 1 -Dimensional


-----------------  Printing the Arrays  ------------------------
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[b'Iris-setosa' b'Iris-setosa' b'Iris-setosa' b'Iris-setosa'
 b'Iris-setosa']


#### Additional Checks

- The code below are just some extra lines that I wrote to double-check if I actually created the `iris_label` and `iris_data` arrays in the correct order when compared to the `iris` dataset.

In [507]:
##I am checking to see if the length (or number of rows) for both arrays match 
#print(len(iris_data) == len(iris_label)) #output: true

##I also wanted to double check if my technique of creating the arrays match with the original arrays that I created earilier
#iris_data_bool = (iris_data == iris_data_check)
#iris_label_bool = (iris_label == iris_label_check)
#print(iris_data_bool)
#print(iris_label_bool)

## I also found a way to check if 1-Dimensional arrays have all true values or false values. I could only find a way to do this for 1-D arrays
## I don't know if there is a way to check if all boolean values are true for 2-D arrays. So for the iris_data array I would do this check when it was a 1-D array. I have done this in the code block below
#res = all(i for i in iris_label_bool)
#print("Is List completely True ? : " + str(res))

### This code just checks if I correctly created the `iris_data` array correctly (I compare the array with the original array that I created)
### I did check if I correctly created the `iris_label` array correctly but I wanted to check if the values in the `iris_data` 2D array match whats in the original iris dataset
'''
#so I am making a `test_array_2` array which I create from the iris dataset. This would be used to check whether the 
test_array_2 = []
for y in iris:
    test_array_2 = np.append(test_array_2, np.array( list(y)[0:4] ))

test_array_3 = []
for u in iris_data_check:
    test_array_3 = np.append(test_array_3, np.array( list(u)[0:4] ))
    
test_book = (test_array_2 == test_array_3)


res = all(i for i in test_book)
print("Is Boolean check for both *iris_data arrays completely True ? : " + str(res)) #output: all values are true
'''

'\n#so I am making a `test_array_2` array which I create from the iris dataset. This would be used to check whether the \ntest_array_2 = []\nfor y in iris:\n    test_array_2 = np.append(test_array_2, np.array( list(y)[0:4] ))\n\ntest_array_3 = []\nfor u in iris_data_check:\n    test_array_3 = np.append(test_array_3, np.array( list(u)[0:4] ))\n    \ntest_book = (test_array_2 == test_array_3)\n\n\nres = all(i for i in test_book)\nprint("Is Boolean check for both *iris_data arrays completely True ? : " + str(res)) #output: all values are true\n'

### 3B. Split the IRIS dataset by Label [3 points]


Split the dataset in `iris_data` according to the labels `iris_labels`. 

#### Method Number 1

- The code below is my first method of sorting the `iris_data` array based in the unique values in the `iris_labels` array.

In [528]:
# Write your solution here
flower_by_label = {}

##the two statements below do the same thing
#print(set(iris_label)) #output: {b'Iris-versicolor', b'Iris-setosa', b'Iris-virginica'}
#print(list(dict.fromkeys(iris_label))) #output: [b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica']
#flower_by_label[b'Iris-virginica'] = iris_data[iris_label == b'Iris-virginica']

# `set(iris_label)` gives the unique values in the array. so the output is the names of the 3 species
for label in set(iris_label):
    flower_by_label[label] = iris_data[iris_label == label] #this statment creates the dictionary key and then assignes all the numerical values that are associated with the `iris_label` array to that dictionary key
    #print(label)

##prining the first 5 items in each dictionary key
for key in set(iris_label):
    print('\033[1m',key,'\033[0m')
    print(flower_by_label[key][:3])
    print('-----------------')

##printing the entire dictionary
flower_by_label


 b'Iris-versicolor' 
[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]]
-----------------
 b'Iris-setosa' 
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]]
-----------------
 b'Iris-virginica' 
[[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]]
-----------------


{b'Iris-versicolor': array([[7. , 3.2, 4.7, 1.4],
        [6.4, 3.2, 4.5, 1.5],
        [6.9, 3.1, 4.9, 1.5],
        [5.5, 2.3, 4. , 1.3],
        [6.5, 2.8, 4.6, 1.5],
        [5.7, 2.8, 4.5, 1.3],
        [6.3, 3.3, 4.7, 1.6],
        [4.9, 2.4, 3.3, 1. ],
        [6.6, 2.9, 4.6, 1.3],
        [5.2, 2.7, 3.9, 1.4],
        [5. , 2. , 3.5, 1. ],
        [5.9, 3. , 4.2, 1.5],
        [6. , 2.2, 4. , 1. ],
        [6.1, 2.9, 4.7, 1.4],
        [5.6, 2.9, 3.6, 1.3],
        [6.7, 3.1, 4.4, 1.4],
        [5.6, 3. , 4.5, 1.5],
        [5.8, 2.7, 4.1, 1. ],
        [6.2, 2.2, 4.5, 1.5],
        [5.6, 2.5, 3.9, 1.1],
        [5.9, 3.2, 4.8, 1.8],
        [6.1, 2.8, 4. , 1.3],
        [6.3, 2.5, 4.9, 1.5],
        [6.1, 2.8, 4.7, 1.2],
        [6.4, 2.9, 4.3, 1.3],
        [6.6, 3. , 4.4, 1.4],
        [6.8, 2.8, 4.8, 1.4],
        [6.7, 3. , 5. , 1.7],
        [6. , 2.9, 4.5, 1.5],
        [5.7, 2.6, 3.5, 1. ],
        [5.5, 2.4, 3.8, 1.1],
        [5.5, 2.4, 3.7, 1. ],
        [5.8, 2.7, 3

#### Additional Check Dataset

- I have created a additional dictionary called `flower_by_label_check` which uses the `iris_data_check` and `iris_label_check` arrays to create the dictionary. These variables were created in **Question 3A - Method 1**. I am doing this additional check to see if my work in **Question 3A - Method 2** was correct because if it was then the `flower_by_label_check` dictionary would be the same as the `flower_by_label` dictionary

In [534]:
# the 'flower_by_label_check' dictionary is the same as the previous dictionary. The only difference here is that I am using the
# 'iris_data_check' and 'iris_label_check' variables to create this dictionary so I can double-check if I created my initial dictionary correctly

flower_by_label_check = {}

#print(set(iris_label)) #output: {b'Iris-versicolor', b'Iris-setosa', b'Iris-virginica'}
#print(iris_label_check)
#print(iris_data_check)

for label in set(iris_label_check):
    flower_by_label_check[label] = iris_data_check[iris_label_check == label]

#printing the dictionary
#flower_by_label_check

#### Checking both dictionary values (seeing if `flower_by_label` and `flower_by_label_check` have the same values)

- I am doing this check to see if the variables created in **Question 3A - Method 1** and **Question 3A - Method 2** were correct. The goal of doing the separate methods was to see if my alternative method of creating the 1D and 2D arrays were correct 

In [540]:
## This is to check if the values of both dictionaries are the same (I created the 'flower_by_label_check' dictionary using the initial variables from problem 3a)
## I did this so I can double check whether I have the correct values and made the dictonary correct (keeping order in mind)
#print(flower_by_label.keys()) #output: dict_keys([b'Iris-setosa', b'Iris-versicolor', b'Iris-virginica'])

for key in flower_by_label.keys():
    #print(key)
    bool_matrix = flower_by_label[key] == flower_by_label_check[key] #what `bool_matrix` essentially does creates a matirx of true or false values based on the values in each dictionary key
    
    #after I have created the `bool_matrix` I then check whether all values in the bool matrix are true
    print('The `flower_by_label` and `flower_by_label_check` dictionaries in the',
          key,
          'key are the same since all the boolean outputs in the `bool_matrix are',
          all(all(row) for row in bool_matrix)) #this checks if all boolean values are true
    print()
    #print(all(not all(row) for row in bool_matrix)) #this checks is all values are false -this is why the output is false
    #print(all(all(row) for row in bool_matrix))
    
    #use any() instead of all(). all() return true if all items in an iterable object are true. any() Returns True if any item in an iterable object is true

The `flower_by_label` and `flower_by_label_check` dictionaries in the b'Iris-versicolor' key are the same since all the boolean outputs in the `bool_matrix are True

The `flower_by_label` and `flower_by_label_check` dictionaries in the b'Iris-setosa' key are the same since all the boolean outputs in the `bool_matrix are True

The `flower_by_label` and `flower_by_label_check` dictionaries in the b'Iris-virginica' key are the same since all the boolean outputs in the `bool_matrix are True



### 4. Compute statistics with Numpy [5 points]

1) For each flower species compute the key statistics for `sepal width`:
- mean
- median
- standard deviation

Answer the following questions:

    a) Which is the flower type with the largest mean value for `sepal_width`?
    b) Which is the flower type with the smallest median value for `sepal_width`?
    
2) Compute the correlation matrix between `sepal_width` and `petal_length` for the three scpecies. Which is the species that shows the highest correlation among the two parameters?

### Question Answers

Before I show my work I would like to answer the questions presented:

##### 4.1) Key statistics for `sepal_width`:



|                             |   Iris-setosa  |  Iris-versicolor  | Iris-virginica  |
|-----------------------------|----------------|-------------------|-----------------|
|Mean                         |3.418 cm.       | 2.77 cm.          | 2.974 cm.       |
|Median                       |3.4 cm.         | 2.8 cm.           | 3 cm.           |
|Standard Deviation (pop)     |0.377 cm.       | 0.311 cm.         | 0.319 cm.       |
|Standard Deviation (sample)  |0.381 cm.       | 0.314 cm.         | 0.322 cm.       |

##### 4.a) Which is the flower type with the largest mean value for `sepal_width`?

- Iris-setosa with a maximum `sepal_width` mean of **3.418 cm.**

##### 4.b) Which is the flower type with the smallest median value for `sepal_width`?

- Iris-versicolor with a `sepal_width` median of **2.8 cm.**

##### 4.2) Compute the correlation matrix between `sepal_width` and `petal_length` for the three scpecies. Which is the species that shows the highest correlation among the two parameters?

- Iris-versicolor shows the highest correlation between the `sepal_width` and `petal_length` variables which a correlation coefficient of **0.561**

|                                                            |   Iris-setosa  |  Iris-versicolor  | Iris-virginica  |
|------------------------------------------------------------|----------------|-------------------|-----------------|
|Correlation Coefficient of `sepal_width` and `petal_length` |0.177           |0.561              |0.401            |


#### My work for calculating the key statisitcs of `sepal_width` (Method 1)

In [544]:
### Compute mean, median, and standard deviation for `sepal width` here:

statistics = {} #I am creating a dictionary to store the key statisitcs info.
for label, dataset in flower_by_label.items(): #so the label will represent the keys in the `flower_by_label` dictionary. the dataset will be the values in the keys

    #print(label)
    #print(dataset)
    statistics[label] = {
        'mean': np.mean(dataset, axis=0), #`axis=0` represents rows and will calculate the values vertically. Getting one value from each row
        'median': np.median(dataset, axis=0),
        'population standard deviation': np.std(dataset, axis=0),
        'sample standard deviation' : np.std(dataset, axis = 0, ddof=1)
}

    
#I am printing the results in a nice format here 
for x in statistics:
    print('--------------------------------')
    print('#######',x,'#######')
    print('--------------------------------')
    for y in statistics[x]:
        print('###','\033[1m',y,'\033[0m','###')
        print(statistics[x][y])
print('--------------')    
#also printing the whole dictionary to see how it looks like as a whole
statistics
#print(flower_by_label.items())

--------------------------------
####### b'Iris-versicolor' #######
--------------------------------
###  mean  ###
[5.936 2.77  4.26  1.326]
###  median  ###
[5.9  2.8  4.35 1.3 ]
###  population standard deviation  ###
[0.511 0.311 0.465 0.196]
###  sample standard deviation  ###
[0.516 0.314 0.47  0.198]
--------------------------------
####### b'Iris-setosa' #######
--------------------------------
###  mean  ###
[5.006 3.418 1.464 0.244]
###  median  ###
[5.  3.4 1.5 0.2]
###  population standard deviation  ###
[0.349 0.377 0.172 0.106]
###  sample standard deviation  ###
[0.352 0.381 0.174 0.107]
--------------------------------
####### b'Iris-virginica' #######
--------------------------------
###  mean  ###
[6.588 2.974 5.552 2.026]
###  median  ###
[6.5  3.   5.55 2.  ]
###  population standard deviation  ###
[0.629 0.319 0.546 0.272]
###  sample standard deviation  ###
[0.636 0.322 0.552 0.275]
--------------


{b'Iris-versicolor': {'mean': array([5.936, 2.77 , 4.26 , 1.326]),
  'median': array([5.9 , 2.8 , 4.35, 1.3 ]),
  'population standard deviation': array([0.511, 0.311, 0.465, 0.196]),
  'sample standard deviation': array([0.516, 0.314, 0.47 , 0.198])},
 b'Iris-setosa': {'mean': array([5.006, 3.418, 1.464, 0.244]),
  'median': array([5. , 3.4, 1.5, 0.2]),
  'population standard deviation': array([0.349, 0.377, 0.172, 0.106]),
  'sample standard deviation': array([0.352, 0.381, 0.174, 0.107])},
 b'Iris-virginica': {'mean': array([6.588, 2.974, 5.552, 2.026]),
  'median': array([6.5 , 3.  , 5.55, 2.  ]),
  'population standard deviation': array([0.629, 0.319, 0.546, 0.272]),
  'sample standard deviation': array([0.636, 0.322, 0.552, 0.275])}}

#### My work for calculating the key statisitcs of `sepal_width` (Method 2)

In [579]:
### Compute mean, median, and standard deviation for `sepal width` here:

iris_flower_stats = {}
for key in flower_by_label.keys(): #I am only looping over the `key` here and am not including the dataset
    
    iris_flower_stats[key] = {
        'mean' : np.mean(flower_by_label[key], axis=0), #I access the dataset by using `flower_by_label[key]` but it performs the same action as in method 1
        'median' :  np.median(flower_by_label[key], axis=0),
        'population standard deviation': np.std(flower_by_label[key], axis=0),
        'sample standard deviation' : np.std(flower_by_label[key], axis = 0, ddof=1)
    }

    
##Printing the statisitics dictionary in a easy to read format    

#I am creating these two additional dictionaries to perform a additional check of the biggest mean and lowest median. Although I have done this check by looking at a dataset I wanted to explore a way to do this using code
iris_flower_mean = {}
iris_flower_median = {}

for x in iris_flower_stats:
    print('--------------------------------')
    print('#######',x,'#######') #the key is printed here
    print('--------------------------------')
    for y in iris_flower_stats[x]:
        print('###','\033[1m',y,'\033[0m','###')  #now the sub-key is printed (in this case the mean,median,SD)
        print(iris_flower_stats[x][y]) #I then print all the mean,median,SD values associated with the dictionary key
        
        #this is where I utlize the `iris_flower_mean` and `iris_flower_median` dictionaries. I create these dictionaries to just check the largest mean and smallest median values for the `sepal_width` variable
        if y == 'mean':
            iris_flower_mean[x] = iris_flower_stats[x][y][1]
            #print(iris_flower_stats[x][y][1]) #output: the mean value of `sepal_width`
        elif y == 'median':
            iris_flower_median[x] = iris_flower_stats[x][y][1]
            #print(iris_flower_median[x][y][1]) #output: the median value of `sepal_width`

--------------------------------
####### b'Iris-versicolor' #######
--------------------------------
###  mean  ###
[5.936 2.77  4.26  1.326]
###  median  ###
[5.9  2.8  4.35 1.3 ]
###  population standard deviation  ###
[0.511 0.311 0.465 0.196]
###  sample standard deviation  ###
[0.516 0.314 0.47  0.198]
--------------------------------
####### b'Iris-setosa' #######
--------------------------------
###  mean  ###
[5.006 3.418 1.464 0.244]
###  median  ###
[5.  3.4 1.5 0.2]
###  population standard deviation  ###
[0.349 0.377 0.172 0.106]
###  sample standard deviation  ###
[0.352 0.381 0.174 0.107]
--------------------------------
####### b'Iris-virginica' #######
--------------------------------
###  mean  ###
[6.588 2.974 5.552 2.026]
###  median  ###
[6.5  3.   5.55 2.  ]
###  population standard deviation  ###
[0.629 0.319 0.546 0.272]
###  sample standard deviation  ###
[0.636 0.322 0.552 0.275]


#### Checking the largest mean and lowest median value for `sepal_width` through code

In [550]:
#print(iris_flower_mean) #just wanted to see the whole dictionary and verify if it correctly gathered all the mean values

##getting the largest mean value
# `max(iris_flower_mean, key = iris_flower_mean.get)` retrives the key value that containes the highest mean value. the output is `Iris-setosa`
# `iris_flower_mean[max(iris_flower_mean, key = iris_flower_mean.get)]` retrives the value stored in the dictionary key (of the species) that has the highest mean value
print(max(iris_flower_mean, key = iris_flower_mean.get), '|', iris_flower_mean[max(iris_flower_mean, key = iris_flower_mean.get)])

##getting the smallest median value
print(min(iris_flower_median, key = iris_flower_median.get), '|', iris_flower_median[min(iris_flower_median, key = iris_flower_median.get)])

b'Iris-setosa' | 3.41800000667572
b'Iris-versicolor' | 2.799999952316284


#### Calculating the correlation matrix/coefficient (step 1: creating the `sepal_width` and `petal_length` dataset)
- Before I calculate the correlation matrix between `sepal_width` and `petal_length` I need to make sure that I create a new dataframe that only containes those two variables which is what I do below

In [551]:
flower_by_label_2 = {} #here is the new dictionary that will contain values from `sepal_width` and `petal_length` only

for key in flower_by_label:
    list_2 = [] #this list would store all the values of `sepal_width` and `petal_length` from the `flower_by_label` dictionary
    
    i = 0 #I just created this variable to double-check and count the number of rows that I would need in my matrix when reshape it
    for y in flower_by_label[key]: #this for loop will now access all the contents (numbers) in each dictionary key in `flower_by_label`
        list_2 = np.append(list_2, np.array(list(y)[1:3])) #I am now indexing and adding the `sepal_width` and `petal_length` values to this list
        i = i +1
        
    #print(i)
    flower_by_label_2[key] = list_2.reshape(50,2) #after I am done gathering all the values I then reshape the list to represent the original order and length of the `flower_by_label` dictionary
    
    
flower_by_label_2 #printing the new dictionary which only containes values from `sepal_width` and `petal_length`

{b'Iris-versicolor': array([[3.2, 4.7],
        [3.2, 4.5],
        [3.1, 4.9],
        [2.3, 4. ],
        [2.8, 4.6],
        [2.8, 4.5],
        [3.3, 4.7],
        [2.4, 3.3],
        [2.9, 4.6],
        [2.7, 3.9],
        [2. , 3.5],
        [3. , 4.2],
        [2.2, 4. ],
        [2.9, 4.7],
        [2.9, 3.6],
        [3.1, 4.4],
        [3. , 4.5],
        [2.7, 4.1],
        [2.2, 4.5],
        [2.5, 3.9],
        [3.2, 4.8],
        [2.8, 4. ],
        [2.5, 4.9],
        [2.8, 4.7],
        [2.9, 4.3],
        [3. , 4.4],
        [2.8, 4.8],
        [3. , 5. ],
        [2.9, 4.5],
        [2.6, 3.5],
        [2.4, 3.8],
        [2.4, 3.7],
        [2.7, 3.9],
        [2.7, 5.1],
        [3. , 4.5],
        [3.4, 4.5],
        [3.1, 4.7],
        [2.3, 4.4],
        [3. , 4.1],
        [2.5, 4. ],
        [2.6, 4.4],
        [3. , 4.6],
        [2.6, 4. ],
        [2.3, 3.3],
        [2.7, 4.2],
        [3. , 4.2],
        [2.9, 4.2],
        [2.9, 4.3],
        [2.5, 3. ],


#### Calculating the correlation matrix/coefficient 
- Now that I have a dictionary that strictly stores the values of `sepal_width` and `petal_length`. I can now create the correlation matrix

In [557]:
# solving for the covariance martrix
cov_mat = {
    label: dict(cov=np.cov(dataset.T, ddof=0)) for label, dataset in flower_by_label_2.items()
}

#print(cov_mat)
#print('-------------------------------------')

# Compute the correlation matrix here
cor_mat = {
    label: dict(cov=np.corrcoef(dataset.T)) for label, dataset in flower_by_label_2.items()
}
print(cor_mat)

#Displaying the correlation matrix in a easy to read format
for x in cor_mat:
    print('--------------------------------')
    print('#######',x,'#######')
    print('--------------------------------')
    for y in cor_mat[x]:
        print('###','\033[1m',y,'\033[0m','###')
        print(cor_mat[x][y])

{b'Iris-versicolor': {'cov': array([[1.   , 0.561],
       [0.561, 1.   ]])}, b'Iris-setosa': {'cov': array([[1.   , 0.177],
       [0.177, 1.   ]])}, b'Iris-virginica': {'cov': array([[1.   , 0.401],
       [0.401, 1.   ]])}}
--------------------------------
####### b'Iris-versicolor' #######
--------------------------------
###  cov  ###
[[1.    0.561]
 [0.561 1.   ]]
--------------------------------
####### b'Iris-setosa' #######
--------------------------------
###  cov  ###
[[1.    0.177]
 [0.177 1.   ]]
--------------------------------
####### b'Iris-virginica' #######
--------------------------------
###  cov  ###
[[1.    0.401]
 [0.401 1.   ]]


### 5. Create a new column from existing columns of a numpy array [5 points]

Create a new column for the flower volume V in `iris`, where volume is computing according to this formula (the assumption here is that the shape of the iris flower is approximately conical):

$$ Volume = \frac{\pi \times Sepal Length^2 \times Petal Length}{3}$$

In [566]:
import math
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

'''iris = np.genfromtxt(url, delimiter=',', 
                     names=['sepal length', 'sepal width', 'petal length', 'petal width', 'species'],
                     dtype=[np.float32, np.float32, np.float32, np.float32, '|S15']
)'''
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')
# Write your solution here
iris_2d_list = [] #I am creating this list and will make it multi-dimensional. This list will contain the `volume` column and will be used to create the pandas dataframe in question 6

#iris_2d = iris_2d.reshape(150,6)
for x in iris_2d:    
    x[0:4] = x[0:4].astype(str).astype(float) #this converts all four length and width columns into a float type 
    x[4] = str(x[4], 'UTF-8') #this converts the species column into a string
    
    x = np.append(x, (math.pi* x[0]**2 * x[2])/3 ) #I am creating the `volume` column and use the append function to add the volume in each row of the `iris_2d` dataset      
    iris_2d_list.append(x) #this creates dynamic multidimensional list which allows the dataframe to formlater on
    

#print(iris_2d.dtype) #output: object
#print(iris_2d_list[:5]) #the output here confirms that the list formed is a multidimensional array
i = 0
for x in iris_2d_list:
    if i < 5:
        print(x)
    i = i +1


[5.1 3.5 1.4 0.2 'Iris-setosa' 38.13265162927291]
[4.9 3.0 1.4 0.2 'Iris-setosa' 35.200498485922445]
[4.7 3.2 1.3 0.2 'Iris-setosa' 30.0723720777127]
[4.6 3.1 1.5 0.2 'Iris-setosa' 33.238050274980004]
[5.0 3.6 1.4 0.2 'Iris-setosa' 36.65191429188092]


### 6A. Convert the numpy array into a pandas DataFrame [2 points]

Convert the all the columns of the numpy array into a Pandas DataFrame. Test this has worked successfully by printing a random sample of ten rows (records) from the new DataFrame. 

In [577]:
# Write your solution here

#print(pd.DataFrame(iris_2d_list)) #I am printing the multi-dimensional list that I created in Q5 as a pandas dataframe

df = pd.DataFrame(iris_2d_list) #converting the list to a dataframe
df = df.rename(columns ={0:'sepal_length',1:'sepal_width',2:'petal_length',3:'petal_width',4:'species',5 : 'volume'} ) #converting the column names of the dataframe

print(df[:10]) #printing the dataframe
print()
print('----------------Random Sample of 10 Rows---------------------')
print(df.sample(n = 10, replace = False)) #printing a random sample of 10 rows from the dataframe

   sepal_length  sepal_width  petal_length  petal_width      species  volume
0          5.10         3.50          1.40         0.20  Iris-setosa   38.13
1          4.90         3.00          1.40         0.20  Iris-setosa   35.20
2          4.70         3.20          1.30         0.20  Iris-setosa   30.07
3          4.60         3.10          1.50         0.20  Iris-setosa   33.24
4          5.00         3.60          1.40         0.20  Iris-setosa   36.65
5          5.40         3.90          1.70         0.40  Iris-setosa   51.91
6          4.60         3.40          1.40         0.30  Iris-setosa   31.02
7          5.00         3.40          1.50         0.20  Iris-setosa   39.27
8          4.40         2.90          1.40         0.20  Iris-setosa   28.38
9          4.90         3.10          1.50         0.10  Iris-setosa   37.71

----------------Random Sample of 10 Rows---------------------
     sepal_length  sepal_width  petal_length  petal_width          species  \
113         

### 6B. Display the mean flower volume for each of the flower types [3 points]
Providing that you've calculated the flower volume for each row in Q5, now calculate and display the mean volumes for each of the three flower types.

In [578]:
#Write your solution here

#print(df["volume"].mean())

for entry in df['species'].unique(): #`df['species'].unique()` prints the unique values in the `species` column which are the 3 flower species
    check = df["species"]==entry #the `check` variable prints all the volume values for each species
    #print('-----------')
    print('The mean volume of', entry, 'is:', df[check]["volume"].mean())
    print('-----------')

The mean volume of Iris-setosa is: 38.76237340470947
-----------
The mean volume of Iris-versicolor is: 160.5600356287936
-----------
The mean volume of Iris-virginica is: 258.80760722723386
-----------
